### PR TITLE
Updated from network content collector

### PR DESCRIPTION
**Pull request by CaptTrews**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/284
Depends-On: https://github.com/ansible-network/ansible_collections.ansible.netcommon/pull/2
Signed-off-by: CaptTrews <capttrews@gmail.com>

### CODE REVIEW

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now a2a33c12f6ff53313ae7a9a03e5a45bb03f17700

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 8d9c6d6cda19ef6fedae3a66f8c84dbfc98636b7

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 79fcfed36b63f6717f56436f86795ca706b67707

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 8e1780c7a588e70c4fd8704937320533d3d79df0

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now bf238a91b35feff2663d7e00cd6027e37eb89fc9

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now d6326ad180299a4ca66d9d4983e06ca2d5f02a11

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 65788bbbf2fcdbae26bfe4451360c70e5a2fbff3

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now f5489bf67d24d5bc8a83614ee7f154ef4c18b7f8

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now bb0496f06eb3c92b44d2c5e6d609295ea89143da

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now c9d24f99a4ed1292ce5ddf6714a5858a92c57756

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 4f4fbbe9b733b747ea2e06ae1bfab69a53620471

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 5ad4405c942b5a8ac3fc919057d4c69ede609f4b

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now c7302eed43bdbce5b416561854d1f513f2ce0ec9

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 16d612049e505414a0b8456f86b2bafc1f80bc0e

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now c053226806a3121f8d200b17f921885b13445da7

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 2ca93ab7b4f59a0dfc153441c1530b005b20ef5c

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 05d5bb3415657f46d57dd9bfc670c5cd2deb9683

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now cf107df6ff5f60540982a4f59544a9fdc093ef7f

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now e3191ff058b388b527b743c62bf9663c02cc8246

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 46f65d01e4c3a3b6a6f0469222175fedf483f417

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 693fc22c6c1a0a0d36f115169e937f0b5629ec13

**Pull request merged**
