### PR TITLE
Updated from network content collector

### PR DESCRIPTION
**Pull request by CaptTrews**
Signed-off-by: CaptTrews <capttrews@gmail.com>
Depends-On: https://github.com/ansible/ansible/pull/62596

### CODE REVIEW

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 8935d7442d5e7be5920598cf6c2dc7e06ed197e0

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 0958567e4620c10c53cd60695cc9287df6772df2

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 5cf18e638f88ab656649b5ce983c17b6406e40aa

**Comment by pabelanger** [comment]
recheck

**Pull request merged**
