### PR TITLE
Updated from network content collector

### PR DESCRIPTION
**Pull request by CaptTrews**
Depends-On: https://github.com/ansible-network/ansible_collections.arista.eos/pull/54
Signed-off-by: CaptTrews <capttrews@gmail.com>

### CODE REVIEW

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 69512c52e9974b8b786e7a2ad0d944a856dad522

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now b74124694a4a1f8d4eeeab0cbfc4c395f5139d64

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 7f0dec8b57ba13efba466d2bfc56cb0b172e9116

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 832a21cf036e7d8d289957f4db3aabf26d89afbd

**Pull request merged**
