### PR TITLE
Updated from network content collector

### PR DESCRIPTION
**Pull request by CaptTrews**
Signed-off-by: CaptTrews <capttrews@gmail.com>

### CODE REVIEW

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 3a32dafffed9db493a415deb2f862c480cd77024

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now a73690487826ef2d3b8b7e8e22aa2a65f6ef9a5a

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now e36060a822348f7c2763c825a7160eeba3bbad6c

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now f5834af0dfcd0d36884a52280573cc8103ea72e5

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now c70b6f657aed852328a7eb6836ff26202be888c1

**Pull request merged**
