### PR TITLE
Updated from network content collector

### PR DESCRIPTION
**Pull request by CaptTrews**
Depends-On: https://github.com/ansible-network/ansible_collections.ansible.netcommon/pull/4
Signed-off-by: CaptTrews <capttrews@gmail.com>

### CODE REVIEW

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now f2df25227b9bc5a96bc19cd51a717469b998ac9a

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 9b33dac6981b3d67080f9653588ab44135912fa3

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 31e8a87610764c0f84802abbfccf71ac4b541962

**Pull request closed without merging**
