### PR TITLE
Updated from network content collector

### PR DESCRIPTION
**Pull request by CaptTrews**
Depends-On: https://github.com/ansible-network/ansible_collections.ansible.netcommon/pull/21
Signed-off-by: CaptTrews <capttrews@gmail.com>

### CODE REVIEW

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 59c09dcbc33ae8ba244a723b4a15cea78fb74f56

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 4118a26f7157c715deac0f3acba3d5427a740099

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 62494262e2a1d63e4de108325602803d8a1a4689

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now b736aae951f3a9d4b511272ae2bb9a6492ac0608

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 4dc1a517b8d17d85bb0c40c88391aa73e9924271

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now ff1e0aed74d412fb75e364518f10f51d9009ec1f

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 098a4269fc6e4b7a27c4bdfa1d141eb0262f6b36

**Pull request closed without merging**
