### PR TITLE
Updated from network content collector

### PR DESCRIPTION
**Pull request by CaptTrews**
Depends-On: https://github.com/ansible-network/ansible_collections.ansible.netcommon/pull/4
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/287
Signed-off-by: CaptTrews <capttrews@gmail.com>

### CODE REVIEW

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 77e4fe652d962c927cd394f592bdc5240129dcc5

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 45c253e0bc81718cf48213e91d7a7eba286dd7d6

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now bddae9783db58c038e2faed8aa74a33af455cd5c

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now aa7850c713093f5ef3fcd0fc92c00eb7e33f7870

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 52e05ce8c5366233680bacd61163d736be551882

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 5f7317d1536e7bdc07e21a06b3647cf33ea92889

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 67e0926c2ccbe8fdd8adfe187ac30d471d5e65dc

**Pull request merged**
