### PR TITLE
Updated from network content collector

### PR DESCRIPTION
**Pull request by CaptTrews**
Depends-On: https://github.com/ansible/ansible/pull/60947
Signed-off-by: CaptTrews <capttrews@gmail.com>

### CODE REVIEW

**Comment by pabelanger** [comment]
recheck

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now a749df4458f3b26057ce91ea4e1a89e1555ead18

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now d2daf2373b886ab9abdfccefa44f8908c344698b

**Comment by CaptTrews** [comment]
Pull-request updated, HEAD is now 30f1a39eece8bc37eeb89f05d733d133c707626e

**Pull request merged**
